import Header from "@/components/header/HeaderBanner";
import HeroSlider from "@/components/header/HeroSlider";
import HoverCards from "@/components/header/HoverCards";
import PottySlider from "@/components/other/PottySlider";
import SliderReviews from "@/components/other/SliderReviews";
import { Icon } from "@iconify/react";
import { Box, Grid, styled, Typography } from "@mui/material";
import Head from "next/head";

const TextHead = styled(Typography)`
  font-weight: 500;
  color: #787878;
  text-align: center;
  font-size: 3.5rem;
  span {
    font-weight: 900;
    color: #3c3a3a;
  }
`;

const TextBody = styled(Typography)`
  font-weight: 500;
  color: #787878;
  text-align: center;
  font-size: 1.25rem;
  span {
    font-weight: 600;
    color: #3c3a3a;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>KinderFlip | Say Goodbye to Diapers</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container>
          <Grid item xs={12}>
            <Header />
          </Grid>
          <Grid item xs={12}>
            <HeroSlider />
          </Grid>
          <Grid item xs={12}>
            <HoverCards />
          </Grid>
          <Grid
            item
            xs={12}
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              flexDirection: "column",
              mx: 30,
              gap: 3,
            }}
          >
            <TextHead variant="h3">
              Say Goodbye To{" "}
              <strong>
                <span>Diapers</span>
              </strong>
            </TextHead>
            <TextBody variant="body2" textAlign="center">
              &quot;
              <span>
                Kinderflip is thrilled to unveil our latest addition:{" "}
              </span>
              the Kids Travel Potty featuring the charming
              <br />
              Wolfy character! Explore our delightful collection, perfect for
              gifting, loving, or becoming your child&apos;s
              <br />
              new favorite travel companion.&quot;
            </TextBody>
          </Grid>
          <Grid item xs={12}>
            <PottySlider />
          </Grid>
          <Grid item xs={12}>
            <TextHead variant="h3">
              Exclusive{" "}
              <strong>
                <span>Accessories</span>
              </strong>
            </TextHead>

            <Grid
              container
              sx={{
                mb: 10,
              }}
            >
              <Grid
                item
                xs={12}
                sx={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  flexDirection: "row",
                  gap: 1,
                  mx: 30,
                  mt: 8,
                }}
              >
                <Box
                  sx={{
                    width: "25%",
                    height: "350px",
                    position: "relative",
                    overflow: "hidden",
                    borderRadius: "20px 20px 0px 20px",
                  }}
                >
                  <div
                    style={{
                      width: "100%",
                      height: "100%",
                      background:
                        "linear-gradient(to top, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0) 40%)",
                      position: "absolute",
                      top: 0,
                      left: 0,
                    }}
                  >
                    <Typography
                      variant="h6"
                      textAlign={"center"}
                      sx={{
                        width: "100%",
                        color: "#fff",
                        position: "absolute",
                        bottom: "5%",
                        fontWeight: 300,
                        fontSize: "1.5rem",
                        lineHeight: "1",
                      }}
                    >
                      Funky
                      <br />
                      <span
                        style={{
                          fontWeight: 900,
                          fontSize: "2rem",
                        }}
                      >
                        Plasters
                      </span>
                    </Typography>
                  </div>
                  <img
                    src="/assets/images/other/funky-plasters.png"
                    alt=""
                    style={{
                      width: "260%",
                      height: "100%",
                      objectFit: "cover",
                    }}
                  />
                </Box>
                <Box
                  sx={{
                    width: "28%",
                    height: "420px",
                    position: "relative",
                    overflow: "hidden",
                    borderRadius: "20px",
                  }}
                >
                  <div
                    style={{
                      width: "100%",
                      height: "100%",
                      background:
                        "linear-gradient(to top, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0) 40%)",
                      position: "absolute",
                      top: 0,
                      left: 0,
                    }}
                  >
                    <Typography
                      variant="h6"
                      textAlign={"center"}
                      sx={{
                        width: "100%",
                        color: "#fff",
                        position: "absolute",
                        bottom: "5%",
                        fontWeight: 300,
                        fontSize: "1.5rem",
                        lineHeight: "1",
                      }}
                    >
                      Tod
                      <br />
                      <span
                        style={{
                          fontWeight: 900,
                          fontSize: "2rem",
                        }}
                      >
                        Wet Wipes
                      </span>
                      <br />
                      <button
                        style={{
                          backgroundColor: "rgba(60, 58, 58, 0.9)",
                          color: "#fff",
                          fontSize: "0.7rem",
                          fontWeight: 500,
                          padding: "5px 50px",
                          borderRadius: "30px",
                          border: "4px solid #fff",
                          cursor: "pointer",
                          margin: "12px 0  0 0",
                        }}
                      >
                        Buy Now
                      </button>
                    </Typography>
                  </div>
                  <img
                    src="/assets/images/other/tod-wet-wipes.png"
                    alt=""
                    style={{
                      width: "130%",
                      height: "100%",
                      objectFit: "cover",
                    }}
                  />
                </Box>
                <Box
                  sx={{
                    width: "25%",
                    height: "350px",
                    position: "relative",
                    overflow: "hidden",
                    borderRadius: "20px 20px 20px 0px",
                  }}
                >
                  <div
                    style={{
                      width: "100%",
                      height: "100%",
                      background:
                        "linear-gradient(to top, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0) 40%)",
                      position: "absolute",
                      top: 0,
                      left: 0,
                    }}
                  >
                    <Typography
                      variant="h6"
                      textAlign={"center"}
                      sx={{
                        width: "100%",
                        color: "#fff",
                        position: "absolute",
                        bottom: "5%",
                        fontWeight: 300,
                        fontSize: "1.5rem",
                        lineHeight: "1",
                      }}
                    >
                      3D
                      <br />
                      <span
                        style={{
                          fontWeight: 900,
                          fontSize: "2rem",
                        }}
                      >
                        Stickers
                      </span>
                    </Typography>
                  </div>
                  <img
                    src="/assets/images/other/3D-Stickers.png"
                    alt=""
                    style={{
                      width: "200%",
                      height: "135%",
                      objectFit: "cover",
                      marginTop: "-60px",
                      marginLeft: "-212.5px",
                    }}
                  />
                </Box>
              </Grid>
            </Grid>
          </Grid>
          <Grid
            item
            xs={12}
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              flexDirection: "column",
              mx: 30,
              gap: 3,
              mt: 1,
            }}
          >
            <TextHead variant="h3">
              Join The Toddlers
              <br />
              <strong>
                <span>Club</span>
              </strong>
            </TextHead>
            <TextBody variant="body2" textAlign="center">
              Become a KinderFlipCC member and get exclusive access
              <br />
              to our premium portal
            </TextBody>

            <img
              src="/assets/images/other/club-membership-card.png"
              alt=""
              style={{
                width: "100%",
                height: "auto",
                maxWidth: "700px",
                marginTop: "-150px",
              }}
            />

            <button
              style={{
                backgroundColor: "#3c3a3a",
                color: "#fff",
                fontSize: "1rem",
                fontWeight: 600,
                padding: "4px 25px",
                borderRadius: "30px",
                border: "5px solid #fff",
                boxShadow: "0px 10px 40px 0px rgba(106, 105, 104, 0.4)",
                cursor: "pointer",
                marginTop: "-50px",
                display: "flex",
                alignItems: "center",
              }}
            >
              Become a Member now&nbsp;&nbsp;
              <Icon icon="gravity-ui:arrow-right" fontSize={28} />
            </button>
          </Grid>
          <Grid item xs={12}>
            <Box
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                flexDirection: "column",
                mx: 30,
                mt: 10,
                height: "190px",
                overflow: "hidden",
                position: "relative", // Added to allow absolute positioning of button
              }}
            >
              <img
                src="/assets/images/other/secondary-banner.png"
                alt="Secondary Banner"
                style={{
                  width: "100%",
                  height: "100%",
                  maxWidth: "800px",
                  objectFit: "cover",
                  borderRadius: "20px",
                }}
              />
              <button
                style={{
                  backgroundColor: "#fff",
                  color: "#000",
                  border: "none",
                  borderRadius: "30px",
                  position: "absolute",
                  zIndex: 2,
                  fontSize: "0.6rem",
                  fontWeight: 600,
                  padding: "4px 18px",
                  bottom: "15px",
                  left: "16%",
                }}
              >
                Explore
              </button>
            </Box>
          </Grid>
          <Grid item xs={12}>
            <SliderReviews />
          </Grid>
          <Grid item xs={12}>
            <Box
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                flexDirection: "column",
                mt: 8,
                height: "200px",
                overflow: "hidden",
                position: "relative", // Add position relative
              }}
            >
              <Box
                component="img"
                src="/assets/images/other/banner-2.png"
                alt=""
                sx={{
                  width: "100%",
                  height: "450%",
                  objectFit: "cover",
                  marginTop: "-580px",
                }}
              />
              <Box
                sx={{
                  position: "absolute", // Position the overlay absolutely
                  top: 0,
                  left: 0,
                  width: "100%",
                  height: "100%",
                  backgroundColor: "rgba(0, 0, 0, 0.4)", // Add the overlay background
                  pointerEvents: "none", // Ensure the overlay does not block interactions
                }}
              />
              <Typography
                variant="h4"
                sx={{
                  position: "absolute", // Position the text absolutely
                  top: "50%", // Center the text vertically
                  left: "50%", // Center the text horizontally
                  transform: "translate(-50%, -50%)", // Adjust the position to truly center the text
                  color: "white", // Text color
                  pointerEvents: "none", // Ensure the text does not block interactions
                  fontSize: "2rem",
                }}
              >
                Made for
                <span
                  style={{
                    fontWeight: 600,
                  }}
                >
                  {" "}
                  Magic
                </span>
              </Typography>
            </Box>
          </Grid>
          <Grid item xs={12}>
            <Box
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                flexDirection: "column",
                height: "450px",
                overflow: "hidden",
                position: "relative", // Add position relative
              }}
            >
              <img
                src="/assets/images/other/banner-3.png"
                alt=""
                style={{
                  width: "145%",
                  height: "300%",
                  objectFit: "cover",
                  marginTop: "-720px",
                  marginLeft: "450px",
                }}
              />
              <Box
                sx={{
                  position: "absolute", // Position the overlay absolutely
                  top: 0,
                  left: 0,
                  width: "100%",
                  height: "100%",
                  backgroundColor: "rgba(0, 0, 0, 0.4)", // Add the overlay background
                  pointerEvents: "none", // Ensure the overlay does not block interactions
                }}
              ></Box>
              <Typography
                sx={{
                  position: "absolute", // Position the text absolutely
                  top: "25%", // Center the text vertically
                  left: "5%", // Center the text horizontally
                  color: "white", // Text color
                  pointerEvents: "none", // Ensure the text does not block interactions
                  fontWeight: 500,
                  fontSize: "5rem",
                  lineHeight: "25px",
                  maxWidth: "900px",
                }}
              >
                Potty Training
                <br />
                <br />
                <br />
                <span
                  style={{
                    fontWeight: 300,
                    fontSize: "1.75rem",
                  }}
                >
                  Patience, consistency, and encouragement are key
                  <br />
                  when it comes to successful potty training, creating a
                  positive
                  <br />
                  and supportive environment for your child.
                </span>
              </Typography>
              <button
                style={{
                  backgroundColor: "#fff",
                  color: "#000",
                  border: "none",
                  borderRadius: "50px",
                  position: "absolute",
                  zIndex: 2,
                  fontSize: "1rem",
                  fontWeight: 600,
                  padding: "10px 45px",
                  bottom: "10%",
                  left: "5%",
                }}
              >
                Explore
              </button>
            </Box>
          </Grid>
          <Grid
            item
            xs={12}
            sx={{
              backgroundColor: "#000",
              color: "#fff",
              p: 5,
            }}
          >
            <Grid container spacing={6}>
              <Grid item xs={12} md={2}>
                <Typography variant="h6">Explorer</Typography>
                <ul
                  style={{
                    listStyleType: "none",
                    padding: 0,
                  }}
                >
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    Electric bikes
                  </li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    City bikes
                  </li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    Kids&apos; bikes
                  </li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    Accessories
                  </li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>Outlet</li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>Business</li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    Insurance Electric
                  </li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    Size guide
                  </li>
                </ul>
              </Grid>
              <Grid item xs={12} md={2}>
                <Typography variant="h6">About</Typography>
                <ul
                  style={{
                    listStyleType: "none",
                    padding: 0,
                  }}
                >
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>About us</li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>Journal</li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>Reviews</li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>Press</li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>Jobs</li>
                </ul>
              </Grid>
              <Grid item xs={12} md={2}>
                <Typography variant="h6">Help</Typography>
                <ul
                  style={{
                    listStyleType: "none",
                    padding: 0,
                  }}
                >
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>Contact</li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>FAQ</li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>Delivery</li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    Assembly & manuals
                  </li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    Payment options
                  </li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    Privacy policy
                  </li>
                  <li style={{ margin: "5px 0", fontWeight: 400 }}>
                    Terms & conditions
                  </li>
                </ul>
              </Grid>
              <Grid item xs={12} md={6}>
                <Typography variant="h6">Join the Fun</Typography>
                <Typography variant="body1" sx={{ my: 3 }}>
                  Sign up for our newsletter.
                </Typography>
                <input
                  type="email"
                  placeholder="Enter your email"
                  style={{
                    width: "600px",
                    padding: "20px 10px 20px 50px",
                    borderRadius: "30px",
                    border: "2px solid #fff",
                    marginTop: "10px",
                    backgroundColor: "#000",
                    color: "#fff",
                    fontSize: "1rem",
                    fontWeight: 500,
                  }}
                />
                <button
                  style={{
                    backgroundColor: "#fff",
                    color: "#000",
                    border: "none",
                    borderRadius: "30px",
                    padding: "22px 50px",
                    marginTop: "10px",
                    cursor: "pointer",
                    position: "relative",
                    float: "right",
                    right: "38px",
                    top: "-72.5px",
                    fontWeight: 600,
                  }}
                >
                  Subscribe
                </button>

                <Typography
                  variant="body1"
                  sx={{ my: 3 }}
                  style={{
                    fontWeight: 500,
                    color: "#fff",
                  }}
                >
                  <input
                    type="checkbox"
                    style={{
                      width: "20px",
                      height: "20px",
                      margin: "0 10px 0 0",
                    }}
                  />{" "}
                  By signing up, I agree to the{" "}
                  <a
                    href="#"
                    style={{
                      color: "#fff",
                    }}
                  >
                    privacy policy
                  </a>{" "}
                  of Veloretti.
                </Typography>
                <Box>
                  <svg
                    width="160"
                    height="16"
                    viewBox="0 0 160 16"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M0.170013 7.99639C0.170013 11.2428 2.52834 13.9425 5.61272 14.4899V9.77364H3.97991V7.95993H5.61272V6.50864C5.61272 4.87614 6.6648 3.96956 8.15283 3.96956C8.62418 3.96956 9.13257 4.04193 9.60384 4.1143V5.78327H8.7695C7.97105 5.78327 7.78981 6.18214 7.78981 6.69039V7.95993H9.53144L9.24136 9.77364H7.78981V14.4899C10.8742 13.9425 13.2325 11.2434 13.2325 7.99639C13.2325 4.38476 10.2935 1.42993 6.70126 1.42993C3.10908 1.42993 0.170013 4.38476 0.170013 7.99639Z"
                      fill="white"
                      fill-opacity="0.9"
                    />
                    <path
                      d="M43.2306 5.16567C41.9453 5.16567 40.8963 6.21464 40.8963 7.5C40.8963 8.78536 41.9453 9.83432 43.2306 9.83432C44.516 9.83432 45.5649 8.78536 45.5649 7.5C45.5649 6.21464 44.516 5.16567 43.2306 5.16567ZM50.2317 7.5C50.2317 6.53335 50.2404 5.57545 50.1862 4.61055C50.1319 3.48979 49.8762 2.49512 49.0567 1.67557C48.2354 0.854259 47.2425 0.600338 46.1218 0.546052C45.1551 0.491765 44.1973 0.500521 43.2324 0.500521C42.2657 0.500521 41.3079 0.491765 40.343 0.546052C39.2222 0.600338 38.2276 0.856011 37.4081 1.67557C36.5868 2.49687 36.3328 3.48979 36.2786 4.61055C36.2243 5.5772 36.233 6.5351 36.233 7.5C36.233 8.4649 36.2243 9.42455 36.2786 10.3894C36.3328 11.5102 36.5885 12.5049 37.4081 13.3245C38.2293 14.1457 39.2222 14.3997 40.343 14.4539C41.3096 14.5083 42.2675 14.4995 43.2324 14.4995C44.199 14.4995 45.1569 14.5083 46.1218 14.4539C47.2425 14.3997 48.2372 14.1439 49.0567 13.3245C49.878 12.5031 50.1319 11.5102 50.1862 10.3894C50.2422 9.42455 50.2317 8.46665 50.2317 7.5ZM43.2306 11.0917C41.2431 11.0917 39.639 9.48759 39.639 7.5C39.639 5.51241 41.2431 3.90832 43.2306 3.90832C45.2182 3.90832 46.8222 5.51241 46.8222 7.5C46.8222 9.48759 45.2182 11.0917 43.2306 11.0917ZM46.9693 4.60004C46.5053 4.60004 46.1305 4.22528 46.1305 3.76122C46.1305 3.29716 46.5053 2.92241 46.9693 2.92241C47.4334 2.92241 47.8081 3.29716 47.8081 3.76122C47.8083 3.87142 47.7867 3.98055 47.7446 4.08239C47.7025 4.18422 47.6407 4.27674 47.5628 4.35467C47.4848 4.43259 47.3923 4.49436 47.2905 4.53647C47.1887 4.57857 47.0795 4.60018 46.9693 4.60004Z"
                      fill="white"
                      fill-opacity="0.9"
                    />
                    <path
                      d="M81.4014 7.37823L79.7637 6.61406C79.6207 6.54771 79.5033 6.62208 79.5033 6.78031V8.21969C79.5033 8.37792 79.6207 8.45229 79.7637 8.38594L81.4006 7.62177C81.5443 7.55469 81.5443 7.44531 81.4014 7.37823ZM80.2325 0.5C76.3665 0.5 73.2325 3.63396 73.2325 7.5C73.2325 11.366 76.3665 14.5 80.2325 14.5C84.0985 14.5 87.2325 11.366 87.2325 7.5C87.2325 3.63396 84.0985 0.5 80.2325 0.5ZM80.2325 10.3438C76.6494 10.3438 76.5867 10.0207 76.5867 7.5C76.5867 4.97927 76.6494 4.65625 80.2325 4.65625C83.8156 4.65625 83.8783 4.97927 83.8783 7.5C83.8783 10.0207 83.8156 10.3438 80.2325 10.3438Z"
                      fill="white"
                      fill-opacity="0.9"
                    />
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M110.233 1.62003C110.233 1.32298 110.351 1.0381 110.561 0.828049C110.771 0.618003 111.055 0.500002 111.353 0.500002H122.518C122.665 0.499761 122.811 0.528558 122.947 0.584744C123.083 0.640931 123.206 0.723403 123.31 0.827439C123.415 0.931475 123.497 1.05504 123.554 1.19104C123.61 1.32704 123.639 1.47282 123.639 1.62003V12.7849C123.639 12.9322 123.61 13.078 123.554 13.2141C123.498 13.3501 123.415 13.4738 123.311 13.5779C123.207 13.6821 123.083 13.7647 122.947 13.821C122.811 13.8773 122.665 13.9063 122.518 13.9062H111.353C111.205 13.9062 111.06 13.8772 110.924 13.8209C110.788 13.7645 110.664 13.682 110.56 13.5779C110.456 13.4738 110.374 13.3503 110.318 13.2143C110.261 13.0784 110.232 12.9327 110.233 12.7855V1.62003ZM115.539 5.61143H117.354V6.52305C117.616 5.99899 118.287 5.52734 119.294 5.52734C121.225 5.52734 121.683 6.57119 121.683 8.48645V12.0342H119.728V8.92276C119.728 7.83199 119.466 7.21652 118.801 7.21652C117.878 7.21652 117.494 7.88013 117.494 8.92276V12.0342H115.539V5.61143ZM112.187 11.9507H114.142V5.52734H112.187V11.9507ZM114.422 3.43231C114.426 3.59969 114.396 3.76612 114.334 3.92183C114.273 4.07754 114.181 4.2194 114.064 4.33908C113.947 4.45876 113.807 4.55385 113.653 4.61876C113.498 4.68368 113.333 4.71712 113.165 4.71712C112.998 4.71712 112.832 4.68368 112.678 4.61876C112.523 4.55385 112.384 4.45876 112.266 4.33908C112.149 4.2194 112.057 4.07754 111.996 3.92183C111.934 3.76612 111.905 3.59969 111.908 3.43231C111.916 3.10377 112.051 2.79112 112.286 2.56132C112.521 2.33153 112.837 2.20285 113.165 2.20285C113.494 2.20285 113.809 2.33153 114.044 2.56132C114.279 2.79112 114.415 3.10377 114.422 3.43231Z"
                      fill="white"
                      fill-opacity="0.9"
                    />
                    <path
                      d="M157.942 3.68524C157.841 3.6333 157.743 3.57634 157.648 3.5146C157.373 3.3323 157.12 3.11749 156.895 2.87482C156.334 2.23224 156.124 1.58036 156.047 1.12396H156.05C155.985 0.745114 156.012 0.5 156.016 0.5H153.457V10.3908C153.457 10.5236 153.457 10.6549 153.452 10.7846C153.452 10.8007 153.45 10.8156 153.449 10.833C153.449 10.8401 153.449 10.8476 153.448 10.855V10.8606C153.421 11.2155 153.307 11.5582 153.117 11.8589C152.926 12.1595 152.664 12.4087 152.355 12.5845C152.032 12.768 151.668 12.8642 151.296 12.8637C150.104 12.8637 149.138 11.8919 149.138 10.6918C149.138 9.49167 150.104 8.5199 151.296 8.5199C151.522 8.51969 151.746 8.55518 151.961 8.62508L151.964 6.02066C151.313 5.93655 150.651 5.9883 150.021 6.17265C149.391 6.35698 148.805 6.66993 148.302 7.09172C147.861 7.47478 147.49 7.93184 147.207 8.44233C147.099 8.62849 146.691 9.37656 146.642 10.5907C146.611 11.2797 146.818 11.9937 146.917 12.2888V12.295C146.979 12.4687 147.219 13.0617 147.611 13.5615C147.927 13.9625 148.3 14.3146 148.719 14.6068V14.6006L148.725 14.6068C149.964 15.4482 151.337 15.393 151.337 15.393C151.575 15.3834 152.371 15.393 153.275 14.9646C154.278 14.4896 154.849 13.7818 154.849 13.7818C155.214 13.3589 155.504 12.877 155.707 12.3567C155.939 11.7483 156.016 11.0185 156.016 10.7269V5.47955C156.047 5.49817 156.46 5.77152 156.46 5.77152C156.46 5.77152 157.056 6.15315 157.985 6.40168C158.651 6.57853 159.549 6.61576 159.549 6.61576V4.0765C159.235 4.11063 158.596 4.01135 157.942 3.68524Z"
                      fill="white"
                      fill-opacity="0.9"
                    />
                  </svg>
                </Box>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </main>
    </>
  );
}
